version: "3.9"
services:
  db:
    container_name: "mysql"
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: vslab
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: vs
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql

  backend:
    container_name: "quarkus-app"
    image: niliit/hse-ss22-vs-lab-backend
    restart: always
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:mysql://db:3306/vslab
      QUARKUS_DATASOURCE_USERNAME: vs
      QUARKUS_DATASOURCE_PASSWORD: password
      QUARKUS_HTTP_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db: